### ISSUE TITLE
Birthday returns as null if year not set

### ISSUE THREAD

**Issue by ghost** [daniochouno/fcontacts#1]
When setting a contacts birthday there is an option to set month and day only, without setting year. But if we don't set year the plugin returns birthday month and day as null as well.

**Comment by ghost** [comment]
Also as a side note, would it be possible to return birthday as a datetime object instead of as day, month and year separately?

**Comment by daniochouno** [comment]
Thanks for your comments @runedrune!

I have fixed this issue and will be included in next version.
From the other hand, I think your note is coherent and I will update the plugin to include the birthday as a FContactDateLabeled inside the 'dates' list in a contact.

**Comment by ghost** [comment]
Oh awesome. Thanks!

Hmm. Actually what I'm trying to accomplish is I want to sort the contacts based on the time till their birthday. That's why if it was in DateTime format it would be easier to sort the list.

**Comment by daniochouno** [comment]
I've published an update for this plugin with the changes we talked. Please update to 1.1.0 version.
Hope this helps you.
